services:
  tdarr:
    extends:
      file: ../../service-base.compose.yaml
      service: arr-service  
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    ports:
      - ${TDARR_UI_PORT}:8265 # webUI port
      - ${TDARR_SERVER_PORT}:8266 # server port
    environment:
      - serverIP=0.0.0.0
      - serverPort=${TDARR_SERVER_PORT}
      - webUIPort=${TDARR_UI_PORT}
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=7
      - nodeName=MyInternalNode
      - auth=false
      - openBrowser=true
      - maxLogSizeMB=10
      - cronPluginUpdate=
    volumes:
      - ./server:/app/server
      - ./configs:/app/configs
      - ${MEDIA_MOVIES_PATH}:/media
      - ${CACHE_DRIVE}/transcode_cache:/temp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TDARR_REF}.entrypoints=web"
      - "traefik.http.routers.${TDARR_REF}.rule=Host(`${HOST_TDARR_URL}`)"
      - "traefik.http.services.${TDARR_REF}.loadbalancer.server.port=${TDARR_UI_PORT}"
      - homepage.group=Utils
      - homepage.name=TDARR
      - homepage.icon=tdarr.png
      - homepage.showstats=true
      - homepage.href=http://${HOST_TDARR_URL}/
    

