services:
  pinchflat:
    extends:
      file: ../service-base.compose.yaml
      service: arr-service
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat
    environment:
      - BASIC_AUTH_USERNAME=${PINCHFLAT_AUTH_USER}
      - BASIC_AUTH_PASSWORD${PINCHFLAT_AUTH_PASS}
    volumes:
      - ./config:/config
      - ${DOWNLOAD_YOUTUBE_PATH}:/downloads
    ports:
      - ${PINCHFLAT_PORT}:8945
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PINCHFLAT_REF}.entrypoints=web"
      - "traefik.http.routers.${PINCHFLAT_REF}.rule=Host(`${PINCHFLAT_URL}`)"
      - "traefik.http.services.${PINCHFLAT_REF}.loadbalancer.server.port=${PINCHFLAT_PORT}"
      - homepage.group=Media
      - homepage.name=Pinchflat
      - homepage.icon=pinchflat.png
      - homepage.href=http://${PINCHFLAT_URL}/
      - homepage.description=Your next YouTube media manager
    restart: unless-stopped