services:
  checkrr:
    extends:
      file: ../../service-base.compose.yaml
      service: arr-service
    container_name: checkrr
    image: aetaric/checkrr:latest
    volumes:
      - ./config/checkrr.yaml:/etc/checkrr.yaml
      - ./config/checkrr.db:/checkrr.db
    ports:
      - ${CHECKRR_PORT}:8585
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${CHECKRR_REF}.entrypoints=web"
      - "traefik.http.routers.${CHECKRR_REF}.rule=Host(`${CHECKRR_URL}`)"
      - "traefik.http.services.${CHECKRR_REF}.loadbalancer.server.port=${CHECKRR_PORT}"
      - homepage.group=Utils
      - homepage.name=checkrr
      - homepage.icon=web-check.svg
      - homepage.href=http://${CHECKRR_URL}/
      - homepage.description=Checkrr Scans your library files for corrupt media and optionally replaces the files via sonarr and radarr
    restart: on-failure