services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    user: root 
    environment:
      - TZ=${PUID}
      - LOG_LEVEL=info
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
    volumes:
      - ./config:/app/config
      - ./settings.yaml:/app/config/settings.yaml
      - ./docker.yaml:/app/config/docker.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports: 
      - ${HOMEPAGE_UI_PORT}:3000 # homepage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${HOMEPAGE_REF}.entrypoints=web"
      - "traefik.http.routers.${HOMEPAGE_REF}.rule=Host(`${HOST_HOMEPAGE_URL}`)"
      - "traefik.http.services.${HOMEPAGE_REF}.loadbalancer.server.port=${HOMEPAGE_UI_PORT}"
    restart: unless-stopped
