services:
  jellyfin:
    extends:
      file: ./jellyfin.compose.yaml
      service: jellyfin
    environment:
      NVIDIA_VISIBLE_DEVICES: all 
      NVIDIA_DRIVER_CAPABILITIES: all
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]