services:
  sonarr:
    extends:
      file: ../../service-base.compose.yaml
      service: arr-service
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - ./config:/config
      - ${MEDIA_SERIES_PATH}:/tv
    ports:
      - ${SONARR_PORT}:8989
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SONARR_REF}.entrypoints=web"
      - "traefik.http.routers.${SONARR_REF}.rule=Host(`${SONARR_URL}`)"
      - "traefik.http.services.${SONARR_REF}.loadbalancer.server.port=${SONARR_REF}"
      - homepage.group=Arr
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.showstats=true
      - homepage.href=http://${SONARR_URL}/
      - homepage.description=Internet PVR for Usenet and Torrents. 
    restart: unless-stopped