services:
  lidarr:
    extends:
      file: ../../service-base.compose.yaml
      service: arr-service
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    volumes:
      - ./config:/config
      - ${MEDIA_MUSIC_PATH}:/music
      - ${DOWNLOAD_MUSIC_PATH}:/downloads
    ports:
      - ${LIDARR_PORT}:8686
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${LIDARR_REF}.entrypoints=web"
      - "traefik.http.routers.${LIDARR_REF}.rule=Host(`${LIDARR_URL}`)"
      - "traefik.http.services.${LIDARR_REF}.loadbalancer.server.port=${LIDARR_PORT}"
      - homepage.group=Arr
      - homepage.name=Lidarr
      - homepage.icon=lidarr.png
      - homepage.showstats=true
      - homepage.href=http://${LIDARR_URL}/
      - homepage.description= Music collection manager for Usenet and BitTorrent users.
    restart: unless-stopped
